Attempt to resolve bug when no languages are defined
Not entirely sure of repercussions yet. if project supported_languages is set to null (indicating we want to just have languages built from detected i18n json files), this error is thrown:

TypeError: Cannot read property 'shift' of null